version: "2"
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/springboot-xjl/frps
    container_name: frp
    restart: always
    ports:
      - "8088:8088"
      - "4443:4443"
      - "6000:6000"
      - "7000:7000"
      - "7500:7500"
    logging:
        driver: "json-file"
        options:
          max-size: "1k"