version: "2"
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/springboot-xjl/frps
    container_name: frp
    restart: always
    ports:
      - "8088:8088"
    logging:
        driver: "json-file"
        options:
          max-size: "1k"